version: '3'
services:
  tests-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["mvn", "clean", "test", ";", "tail", "-f", "/dev/null"]
    ports:
      - "8090:8090"
    environment:
      - MY_G_TOKEN=${MY_G_TOKEN}
      - FOOTBALL_API_TOKEN=${FOOTBALL_API_TOKEN}