version: '3'
services:
  tests-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - FOOTBALL_API_TOKEN=${FOOTBALL_API_TOKEN}