version: '3'
services:
  tests-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    env_file:
      - .env

  wait:
    image: alpine
    command: tail -f /dev/null
    depends_on:
      - tests-service