version: '3'
services:
  tests-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - MY_G_TOKEN=${MY_G_TOKEN}
      - FOOTBALL_API_TOKEN=${FOOTBALL_API_TOKEN}

  wait:
    image: alpine
    command: tail -f /dev/null
    depends_on:
      - tests-service